-- ============================================================================
-- AFTERWORD COMMUNITY HUB — SUPABASE DATABASE SCHEMA (PostgreSQL)
-- ============================================================================

-- Drop tables if needed for clean re-runs (in reverse dependency order)
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.book_loans CASCADE;
DROP TABLE IF EXISTS public.event_rsvps CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.books CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ----------------------------------------------------------------------------
-- 1. USER PROFILES (Linked directly to Supabase Auth auth.users)
-- ----------------------------------------------------------------------------
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    patron_code VARCHAR(30) UNIQUE,
    full_name VARCHAR(100),
    role VARCHAR(20) DEFAULT 'customer' CHECK (role IN ('customer', 'staff', 'admin')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger to automatically create a profile whenever a new user signs up in Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, patron_code, role)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', SPLIT_PART(NEW.email, '@', 1)),
        '#MEM-' || LPAD(FLOOR(RANDOM() * 900 + 100)::TEXT, 3, '0'),
        COALESCE(NEW.raw_user_meta_data->>'role', 'customer')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ----------------------------------------------------------------------------
-- 2. CATEGORIES
-- ----------------------------------------------------------------------------
CREATE TABLE public.categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL                    -- 'cafe', 'flowers', 'books', 'events'
);

-- ----------------------------------------------------------------------------
-- 3. BOOKS (Library Catalog)
-- ----------------------------------------------------------------------------
CREATE TABLE public.books (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(30) UNIQUE,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(150) NOT NULL,
    description TEXT,
    category_id BIGINT REFERENCES public.categories(category_id) ON DELETE SET NULL,
    publisher VARCHAR(150),
    year_published INT,
    shelf_location VARCHAR(50),
    total_copies INT NOT NULL DEFAULT 1 CHECK (total_copies >= 0),
    available_copies INT NOT NULL DEFAULT 1 CHECK (available_copies >= 0),
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 4. PRODUCTS (Café Menu & Botanical Stems)
-- ----------------------------------------------------------------------------
CREATE TABLE public.products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(category_id) ON DELETE SET NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
    stock INT DEFAULT 0 CHECK (stock >= 0),
    image_url TEXT,
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 5. EVENTS (Community Calendar)
-- ----------------------------------------------------------------------------
CREATE TABLE public.events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    category_id BIGINT REFERENCES public.categories(category_id) ON DELETE SET NULL,
    event_date DATE NOT NULL,
    event_time TIME NOT NULL,
    capacity INT NOT NULL CHECK (capacity > 0),
    location VARCHAR(150),
    status VARCHAR(30) DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Completed', 'Cancelled')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 6. ORDERS & ORDER ITEMS (Order Tray)
-- ----------------------------------------------------------------------------
CREATE TABLE public.orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(30) UNIQUE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    order_type VARCHAR(20) DEFAULT 'in_seat' CHECK (order_type IN ('in_seat', 'counter_pickup')),
    table_number INT,
    subtotal DECIMAL(10,2) NOT NULL CHECK (subtotal >= 0),
    tax DECIMAL(10,2) NOT NULL CHECK (tax >= 0),
    total DECIMAL(10,2) NOT NULL CHECK (total >= 0),
    status VARCHAR(30) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Preparing', 'Ready', 'Completed', 'Cancelled')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(product_id) ON DELETE RESTRICT,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price DECIMAL(10,2) NOT NULL CHECK (unit_price >= 0),
    CONSTRAINT unique_order_product UNIQUE (order_id, product_id)
);

-- ----------------------------------------------------------------------------
-- 7. CIRCULATION & RESERVATIONS
-- ----------------------------------------------------------------------------
CREATE TABLE public.book_loans (
    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES public.books(book_id) ON DELETE RESTRICT,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status VARCHAR(30) DEFAULT 'Requested' CHECK (status IN ('Requested', 'Borrowed', 'Returned', 'Overdue', 'Cancelled')),
    borrowed_at TIMESTAMPTZ DEFAULT NOW(),
    due_date DATE NOT NULL,
    returned_at TIMESTAMPTZ
);

CREATE TABLE public.event_rsvps (
    rsvp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    guest_count INT NOT NULL DEFAULT 1 CHECK (guest_count > 0),
    status VARCHAR(30) DEFAULT 'Confirmed' CHECK (status IN ('Confirmed', 'Cancelled', 'Waitlist')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_event_rsvp UNIQUE (event_id, user_id)
);

CREATE TABLE public.wishlists (
    wishlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES public.books(book_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_book_wishlist UNIQUE (user_id, book_id)
);

CREATE TABLE public.book_donations (
    donation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    book_title VARCHAR(200) NOT NULL,
    author VARCHAR(150) NOT NULL,
    summary TEXT,
    publisher VARCHAR(150),
    year_published INT,
    category VARCHAR(100),
    condition VARCHAR(50) DEFAULT 'Good',
    donor_note TEXT,
    donor_name VARCHAR(150) NOT NULL,
    donor_email VARCHAR(150) NOT NULL,
    status VARCHAR(30) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Received', 'Added to Library')),
    admin_note TEXT,
    email_status VARCHAR(30) DEFAULT 'Not Sent' CHECK (email_status IN ('Not Sent', 'Sent', 'Failed')),
    email_sent_at TIMESTAMPTZ,
    email_error TEXT,
-- ----------------------------------------------------------------------------
-- 8. PHYSICAL CAFÉ SEATING TABLES & TABLE RESERVATIONS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cafe_tables (
    table_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number VARCHAR(10) UNIQUE NOT NULL,      -- e.g. 'T01', 'T02', ... 'T16'
    capacity INT NOT NULL CHECK (capacity > 0),    -- e.g. 2, 4, 6, 8, 10
    location VARCHAR(100) NOT NULL,                -- 'Window Alcove', 'Main Hall', 'Communal Table', 'Reading Lounge'
    status VARCHAR(30) DEFAULT 'available' CHECK (status IN ('available', 'occupied', 'reserved', 'unavailable')),
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.table_reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT REFERENCES public.cafe_tables(table_id) ON DELETE CASCADE,
    table_number VARCHAR(10) NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    patron_name VARCHAR(150) NOT NULL,
    patron_email VARCHAR(150) NOT NULL,
    patron_phone VARCHAR(50),
    reservation_date DATE NOT NULL,
    start_time VARCHAR(20) NOT NULL,              -- e.g. '17:00' or '5:00 PM'
    end_time VARCHAR(20),                        -- e.g. '18:30' or '6:30 PM'
    guest_count INT NOT NULL CHECK (guest_count > 0),
    status VARCHAR(30) DEFAULT 'Confirmed' CHECK (status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')),
    special_requests TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


-- ----------------------------------------------------------------------------
-- 8. INDEXES FOR PERFORMANCE
-- ----------------------------------------------------------------------------
CREATE INDEX idx_products_category ON public.products(category_id);
CREATE INDEX idx_books_category ON public.books(category_id);
CREATE INDEX idx_orders_user ON public.orders(user_id);
CREATE INDEX idx_order_items_order ON public.order_items(order_id);
CREATE INDEX idx_order_items_product ON public.order_items(product_id);
CREATE INDEX idx_book_loans_user ON public.book_loans(user_id);
CREATE INDEX idx_book_loans_book ON public.book_loans(book_id);
CREATE INDEX idx_event_rsvps_event ON public.event_rsvps(event_id);
CREATE INDEX idx_event_rsvps_user ON public.event_rsvps(user_id);

-- ----------------------------------------------------------------------------
-- 9. ROW LEVEL SECURITY (RLS) POLICIES
-- ----------------------------------------------------------------------------
-- Enable RLS on all tables
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.book_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_rsvps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;

-- Allow public read access to catalog data (books, products, events, categories)
CREATE POLICY "Public categories are viewable by everyone" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public books are viewable by everyone" ON public.books FOR SELECT USING (true);
CREATE POLICY "Public products are viewable by everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Public events are viewable by everyone" ON public.events FOR SELECT USING (true);

-- Profiles: Anyone can view basic patron info, users can edit their own profile
CREATE POLICY "Profiles are viewable by authenticated users" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Orders & Items: Users can create orders, and read their own orders
CREATE POLICY "Anyone can create orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Users view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "Anyone can insert order items" ON public.order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Users view order items" ON public.order_items FOR SELECT USING (true);

-- RSVPs & Loans & Wishlists: Authenticated users can insert, view, and update their reservations
CREATE POLICY "Users can create event rsvps" ON public.event_rsvps FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own rsvps" ON public.event_rsvps FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create book loans" ON public.book_loans FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own book loans" ON public.book_loans FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own book loans" ON public.book_loans FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own wishlist" ON public.wishlists FOR ALL USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 10. AUTOMATED INVENTORY & RETURN TRIGGERS
-- ----------------------------------------------------------------------------
-- Keeps books.available_copies in perfect sync whenever a loan is created or returned
CREATE OR REPLACE FUNCTION public.handle_book_loan_inventory()
RETURNS TRIGGER AS $$
BEGIN
    -- Case 1: When a loan is allowed & approved by admin (status becomes 'Borrowed')
    IF ((TG_OP = 'INSERT' AND NEW.status = 'Borrowed') OR (TG_OP = 'UPDATE' AND OLD.status = 'Requested' AND NEW.status = 'Borrowed')) THEN
        UPDATE public.books
        SET available_copies = GREATEST(available_copies - 1, 0)
        WHERE book_id = NEW.book_id;

    -- Case 2: When a borrowed book is returned
    ELSIF (TG_OP = 'UPDATE' AND OLD.status = 'Borrowed' AND NEW.status = 'Returned') THEN
        NEW.returned_at := NOW();
        UPDATE public.books
        SET available_copies = LEAST(available_copies + 1, total_copies)
        WHERE book_id = NEW.book_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_book_loan_inventory_change
    BEFORE INSERT OR UPDATE ON public.book_loans
    FOR EACH ROW EXECUTE FUNCTION public.handle_book_loan_inventory();

-- Keeps products.stock and products.is_available in perfect sync whenever an order is placed
CREATE OR REPLACE FUNCTION public.handle_product_order_stock()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.products
    SET 
        stock = GREATEST(stock - NEW.quantity, 0),
        is_available = CASE WHEN (stock - NEW.quantity) <= 0 THEN false ELSE is_available END
    WHERE product_id = NEW.product_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_product_order_stock_change
    AFTER INSERT ON public.order_items
    FOR EACH ROW EXECUTE FUNCTION public.handle_product_order_stock();



